### ISSUE TITLE
mamonazo

### ISSUE THREAD

**Issue by cabrieI** [VictoRPiles/VictoRPiles#3]
_,---._
,' _____ `. ,--  te has copiado el estado de la seta mamon
'-( O O )-'
   \(_)/
    )O(
    """

**Comment by VictoRPiles** [comment]
SLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSASLSA
